name: CI/CD Pipeline - Build & Deploy RAG Service

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: podcarsten-32199
  PROJECT_NUMBER: 573158456254
  REGION: europe-west1
  ARTIFACT_REGISTRY: rag-service-repo
  SERVICE_NAME: rag-service
  SA_EMAIL: github-actions-sa@podcarsten-32199.iam.gserviceaccount.com
  WIF_POOL_ID: github-pool
  WIF_PROVIDER_ID: github-provider
  IMAGE_NAME: rag-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests 
        run: pip install pytest && PYTHONPATH=. pytest .

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL_ID }}/providers/${{ env.WIF_PROVIDER_ID }}
          service_account: ${{ env.SA_EMAIL }}

      - name: Setup gcloud and Configure Docker Helper
        uses: google-github-actions/setup-gcloud@v2
        with:
          docker_helper: true
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Tag Image
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t \$IMAGE_TAG .
          echo "IMAGE_TAG=\$IMAGE_TAG" >> \$GITHUB_ENV

      - name: Push Image to Artifact Registry
        run: docker push ${{ env.IMAGE_TAG }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}
          allow_unauthenticated: true