name: Deploy RAG Service to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: podcarsten-32199
  # The correct European region where your Artifact Registry is hosted (e.g., europe-west1)
  GAR_LOCATION: europe-west1
  SERVICE_NAME: rag-service
  REPOSITORY_NAME: rag-service-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # --- Authentication Step (Workload Identity) ---
    - name: Authenticate Google Cloud with Workload Identity
      uses: 'google-github-actions/auth@v2'
      with:
        # CRITICAL FIX: This input was missing and caused the error.
        # This links the GitHub runner to your Workload Identity Pool setup.
        # The project number (573158456254) is taken from the prior IAM binding output.
        workload_identity_provider: projects/573158456254/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        # The service account to impersonate after successful WIF authentication
        service_account: github-actions-sa@podcarsten-32199.iam.gserviceaccount.com
        
    # --- Docker Build and Push Step ---
    - name: Build and Push Docker Image to Artifact Registry
      id: build-image
      run: |
        # Configure Docker to use gcloud for credentials, using the corrected European location
        gcloud auth configure-docker ${GAR_LOCATION}-docker.pkg.dev --quiet

        # Define the full IMAGE_URI using the corrected location
        IMAGE_URI="${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_NAME}/${SERVICE_NAME}:${GITHUB_SHA}"

        # Build the Docker image
        docker build -t $IMAGE_URI .
        
        # Push the image to Artifact Registry
        docker push $IMAGE_URI

        # Set the image URI as an output for the next step
        echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

    # --- Deploy to Cloud Run Step ---
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        # Deploy to the same region as the registry/service location
        region: ${{ env.GAR_LOCATION }}
        image: ${{ steps.build-image.outputs.image_uri }}
        # Add any necessary runtime flags here...

    - name: Show Service URL
      run: |
        gcloud run services describe ${{ env.SERVICE_NAME }} \
          --platform managed \
          --region ${{ env.GAR_LOCATION }} \
          --format 'value(status.url)'
